# Generated by Django 4.2.2 on 2023-06-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postTwitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='user',
        ),
        migrations.CreateModel(
            name='userPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=210)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postTwitter.user')),
            ],
        ),
    ]
