# Generated by Django 4.2.2 on 2023-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postTwitter', '0002_rename_project_user_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.CharField(max_length=320),
        ),
    ]
